Table governors {
  id int [pk]
  name varchar
  colonyId int [ref: > colonies.id]
  active boolean
}
Table colonies {
  id int [pk]
  name varchar
}
Table miningFacilities {
  id int [pk]
  name varchar
  active boolean
}
Table minerals {
  id int [pk]
  name varchar
}
Table facilityMinerals {
  id int [pk]
  miningFacilityId int [ref: > miningFacilities.id]
  mineralId int [ref: > minerals.id]
  quantity int
}
Table colonyMinerals {
  id int [pk]
  colonyId int [ref: > colonies.id]
  mineralId int [ref: > minerals.id]
  quantity int
}
Table purchases {
  id int [pk]
  governorId int [ref: > governors.id]
  miningFacilityId int [ref: > miningFacilities.id]
  facilityMineralId int [ref: > facilityMinerals.id]
  colonyMineralId int [ref: > colonyMinerals.id]
  quantity int
}